// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using computerChip.Data;

#nullable disable

namespace computerChip.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("computerChip.Models.Admin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("usuario");

                    b.HasKey("id");

                    b.HasIndex("usuario")
                        .IsUnique()
                        .HasDatabaseName("IX_Admin_Usuario");

                    b.ToTable("admin");
                });

            modelBuilder.Entity("computerChip.Models.Atributos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)")
                        .HasColumnName("nombre");

                    b.HasKey("id");

                    b.ToTable("atributos");
                });

            modelBuilder.Entity("computerChip.Models.Carrito", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('activo','abandonado','convertido')")
                        .HasDefaultValue("activo")
                        .HasColumnName("estado");

                    b.Property<DateTime>("updatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("updatedAt"));

                    b.Property<int>("usuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("id");

                    b.HasIndex("usuarioId");

                    b.ToTable("carrito");
                });

            modelBuilder.Entity("computerChip.Models.Categorias", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deletedAt");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("updatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("updatedAt"));

                    b.HasKey("id");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("computerChip.Models.Especificaciones", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("titulo");

                    b.HasKey("id");

                    b.ToTable("especificaciones");
                });

            modelBuilder.Entity("computerChip.Models.Imagenes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deletedAt");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("updatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("updatedAt"));

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("id");

                    b.ToTable("imagenes");
                });

            modelBuilder.Entity("computerChip.Models.ItemPedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Pedidosid")
                        .HasColumnType("int");

                    b.Property<int>("cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantProducto");

                    b.Property<decimal>("subtotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("id");

                    b.HasIndex("Pedidosid");

                    b.ToTable("item_pedido");
                });

            modelBuilder.Entity("computerChip.Models.LoginGoogle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("avatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deletedAt");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<sbyte?>("emailVerificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("email_verificado");

                    b.Property<string>("googleSub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("google_sub");

                    b.Property<string>("nombre")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("refreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("ultimoLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ultimo_login")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("updatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("updatedAt"));

                    b.Property<int>("usuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("id");

                    b.HasIndex("googleSub")
                        .IsUnique()
                        .HasDatabaseName("IX_LoginGoogle_GoogleSub");

                    b.HasIndex("usuarioId");

                    b.ToTable("login_google");
                });

            modelBuilder.Entity("computerChip.Models.Marcas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deletedAt");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("updatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("updatedAt"));

                    b.HasKey("id");

                    b.ToTable("marcas");
                });

            modelBuilder.Entity("computerChip.Models.MetodoPago", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("descuento")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("descuento");

                    b.Property<sbyte>("tieneDesc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("tieneDesc");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("tipo");

                    b.HasKey("id");

                    b.ToTable("metodos_pago");
                });

            modelBuilder.Entity("computerChip.Models.Ofertas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deletedAt");

                    b.Property<decimal>("descuento")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("descuento");

                    b.Property<decimal>("precioOferta")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precioOferta");

                    b.Property<decimal>("precioOriginal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precioOriginal");

                    b.Property<string>("subtitulo")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)")
                        .HasColumnName("subtitulo");

                    b.Property<string>("tipoDescuento")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)")
                        .HasColumnName("tipoDescuento");

                    b.Property<string>("tipoOferta")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)")
                        .HasColumnName("tipoOferta");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("titulo");

                    b.Property<DateTime>("updatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("updatedAt"));

                    b.HasKey("id");

                    b.ToTable("ofertas");
                });

            modelBuilder.Entity("computerChip.Models.Pedidos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int")
                        .HasColumnName("metodos_pago_idmetodos_pago");

                    b.Property<int?>("OfertaId")
                        .HasColumnType("int")
                        .HasColumnName("ofertas_idofertas");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<int>("ZonaEnvioId")
                        .HasColumnType("int")
                        .HasColumnName("zona_envio_idenvio");

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('PENDIENTE','CONFIRMADO','ENVIADO','ENTREGADO','CANCELADO')")
                        .HasDefaultValue("PENDIENTE")
                        .HasColumnName("estado");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.Property<DateTime>("updatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("updatedAt"));

                    b.HasKey("id");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("OfertaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ZonaEnvioId");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("computerChip.Models.Preguntas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("textoPregunta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("textopregunta");

                    b.Property<string>("textoRespuesta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("textorespuesta");

                    b.HasKey("id");

                    b.ToTable("preguntas");
                });

            modelBuilder.Entity("computerChip.Models.Productos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("codigoSerie")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)")
                        .HasColumnName("codigoSerie");

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deletedAt");

                    b.Property<sbyte>("envioGratis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("envioGratis");

                    b.Property<string>("garantia")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)")
                        .HasColumnName("garantia");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.Property<decimal?>("precioOferta")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_oferta");

                    b.Property<sbyte>("stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1)
                        .HasColumnName("stock");

                    b.Property<DateTime>("updatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("updatedAt"));

                    b.HasKey("id");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("computerChip.Models.PushToken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("adminId")
                        .HasColumnType("int")
                        .HasColumnName("Admin_idAdmin");

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("dispositivo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dispositivo");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime>("updatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("updatedAt"));

                    b.Property<int?>("usuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuarios_idusuarios");

                    b.HasKey("id");

                    b.HasIndex("adminId");

                    b.HasIndex("usuarioId");

                    b.ToTable("push_token");
                });

            modelBuilder.Entity("computerChip.Models.SantanderToken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("accessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("expiresIn")
                        .HasColumnType("int")
                        .HasColumnName("expires_in");

                    b.Property<string>("refreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("tokenType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("token_type");

                    b.Property<DateTime>("updatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("updatedAt"));

                    b.Property<int>("usuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("id");

                    b.HasIndex("usuarioId");

                    b.ToTable("santander_token");
                });

            modelBuilder.Entity("computerChip.Models.Soporte", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("email");

                    b.Property<DateTime>("fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("mensaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<string>("nombreCompleto")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("nombreCompleto");

                    b.Property<string>("telefono")
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("telefono");

                    b.HasKey("id");

                    b.ToTable("soporte");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.CarritoProductos", b =>
                {
                    b.Property<int>("carritoId")
                        .HasColumnType("int")
                        .HasColumnName("carrito_id");

                    b.Property<int>("productoId")
                        .HasColumnType("int")
                        .HasColumnName("productos_idproductos");

                    b.Property<int>("cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("precioUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<DateTime>("updatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("updatedAt"));

                    b.HasKey("carritoId", "productoId");

                    b.HasIndex("productoId");

                    b.ToTable("carrito_has_productos");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.CategoriasProductos", b =>
                {
                    b.Property<int>("categoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categorias_idcategorias");

                    b.Property<int>("productoId")
                        .HasColumnType("int")
                        .HasColumnName("productos_idproductos");

                    b.HasKey("categoriaId", "productoId");

                    b.HasIndex("productoId");

                    b.ToTable("categorias_has_productos");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.ItemPedidoProductos", b =>
                {
                    b.Property<int>("itemPedidoId")
                        .HasColumnType("int")
                        .HasColumnName("item_pedido_iditem_pedido");

                    b.Property<int>("productoId")
                        .HasColumnType("int")
                        .HasColumnName("productos_idproductos");

                    b.HasKey("itemPedidoId", "productoId");

                    b.HasIndex("productoId");

                    b.ToTable("item_pedido_has_productos");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.PedidosItemPedido", b =>
                {
                    b.Property<int>("pedidosId")
                        .HasColumnType("int")
                        .HasColumnName("pedidos_idpedidos");

                    b.Property<int>("itemPedidoId")
                        .HasColumnType("int")
                        .HasColumnName("item_pedido_iditem_pedido");

                    b.HasKey("pedidosId", "itemPedidoId");

                    b.HasIndex("itemPedidoId");

                    b.ToTable("pedidos_has_item_pedido");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.ProductosAtributos", b =>
                {
                    b.Property<int>("productoId")
                        .HasColumnType("int")
                        .HasColumnName("productos_idproductos");

                    b.Property<int>("atributoId")
                        .HasColumnType("int")
                        .HasColumnName("atributos_idatributos");

                    b.Property<string>("valor")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("valor");

                    b.HasKey("productoId", "atributoId");

                    b.HasIndex("atributoId");

                    b.ToTable("productos_has_atributos");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.ProductosEspecificaciones", b =>
                {
                    b.Property<int>("productoId")
                        .HasColumnType("int")
                        .HasColumnName("productos_idproductos");

                    b.Property<int>("especificacionId")
                        .HasColumnType("int")
                        .HasColumnName("especificaciones_idespecificaciones");

                    b.HasKey("productoId", "especificacionId");

                    b.HasIndex("especificacionId");

                    b.ToTable("productos_has_especificaciones");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.ProductosImagenes", b =>
                {
                    b.Property<int>("productoId")
                        .HasColumnType("int")
                        .HasColumnName("productos_idproductos");

                    b.Property<int>("imagenId")
                        .HasColumnType("int")
                        .HasColumnName("imagenes_idimagenes");

                    b.Property<int>("orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.HasKey("productoId", "imagenId");

                    b.HasIndex("imagenId");

                    b.ToTable("productos_has_imagenes");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.ProductosMarcas", b =>
                {
                    b.Property<int>("productoId")
                        .HasColumnType("int")
                        .HasColumnName("productos_idproductos");

                    b.Property<int>("marcaId")
                        .HasColumnType("int")
                        .HasColumnName("marcas_idmarcas");

                    b.HasKey("productoId", "marcaId");

                    b.HasIndex("marcaId");

                    b.ToTable("productos_has_marcas");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.ProductosOfertas", b =>
                {
                    b.Property<int>("productoId")
                        .HasColumnType("int")
                        .HasColumnName("productos_idproductos");

                    b.Property<int>("ofertaId")
                        .HasColumnType("int")
                        .HasColumnName("ofertas_idofertas");

                    b.HasKey("productoId", "ofertaId");

                    b.HasIndex("ofertaId");

                    b.ToTable("productos_has_ofertas");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.ProductosPreguntas", b =>
                {
                    b.Property<int>("productoId")
                        .HasColumnType("int")
                        .HasColumnName("productos_idproductos");

                    b.Property<int>("preguntaId")
                        .HasColumnType("int")
                        .HasColumnName("preguntas_idpreguntas");

                    b.HasKey("productoId", "preguntaId");

                    b.HasIndex("preguntaId");

                    b.ToTable("productos_has_preguntas");
                });

            modelBuilder.Entity("computerChip.Models.Usuarios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("calle")
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("calle");

                    b.Property<string>("celular")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("celular");

                    b.Property<string>("ciudad")
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("ciudad");

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deletedAt");

                    b.Property<string>("email")
                        .HasMaxLength(105)
                        .HasColumnType("varchar(105)")
                        .HasColumnName("email");

                    b.Property<sbyte?>("emailVerify")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("email_verify");

                    b.Property<string>("nombreCompleto")
                        .HasMaxLength(105)
                        .HasColumnType("varchar(105)")
                        .HasColumnName("nombreCompleto");

                    b.Property<string>("numero")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("numero");

                    b.Property<string>("pais")
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("pais");

                    b.Property<string>("password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("provincia")
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("provincia");

                    b.Property<DateTime>("updatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("updatedAt"));

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_Email");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("computerChip.Models.ZonaEnvio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ciudad")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("ciudad");

                    b.Property<string>("codigoPostal")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("codigopostal");

                    b.Property<string>("costo")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("costo");

                    b.Property<string>("pais")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("pais");

                    b.Property<string>("provincia")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("provincia");

                    b.HasKey("id");

                    b.ToTable("zona_envio");
                });

            modelBuilder.Entity("computerChip.Models.Carrito", b =>
                {
                    b.HasOne("computerChip.Models.Usuarios", "Usuarios")
                        .WithMany("Carrito")
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("computerChip.Models.ItemPedido", b =>
                {
                    b.HasOne("computerChip.Models.Pedidos", null)
                        .WithMany("Items")
                        .HasForeignKey("Pedidosid");
                });

            modelBuilder.Entity("computerChip.Models.LoginGoogle", b =>
                {
                    b.HasOne("computerChip.Models.Usuarios", "Usuarios")
                        .WithMany("LoginGoogle")
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("computerChip.Models.Pedidos", b =>
                {
                    b.HasOne("computerChip.Models.MetodoPago", "MetodoPago")
                        .WithMany("Pedidos")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("computerChip.Models.Ofertas", "Ofertas")
                        .WithMany("Pedidos")
                        .HasForeignKey("OfertaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("computerChip.Models.Usuarios", "Usuarios")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("computerChip.Models.ZonaEnvio", "ZonaEnvio")
                        .WithMany("Pedidos")
                        .HasForeignKey("ZonaEnvioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MetodoPago");

                    b.Navigation("Ofertas");

                    b.Navigation("Usuarios");

                    b.Navigation("ZonaEnvio");
                });

            modelBuilder.Entity("computerChip.Models.PushToken", b =>
                {
                    b.HasOne("computerChip.Models.Admin", "Admin")
                        .WithMany("PushTokens")
                        .HasForeignKey("adminId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("computerChip.Models.Usuarios", "Usuarios")
                        .WithMany("PushTokens")
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Admin");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("computerChip.Models.SantanderToken", b =>
                {
                    b.HasOne("computerChip.Models.Usuarios", "Usuarios")
                        .WithMany("SantanderTokens")
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.CarritoProductos", b =>
                {
                    b.HasOne("computerChip.Models.Carrito", "Carrito")
                        .WithMany("CarritoProductos")
                        .HasForeignKey("carritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("computerChip.Models.Productos", "Productos")
                        .WithMany("CarritoProductos")
                        .HasForeignKey("productoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.CategoriasProductos", b =>
                {
                    b.HasOne("computerChip.Models.Categorias", "Categorias")
                        .WithMany("CategoriasProductos")
                        .HasForeignKey("categoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("computerChip.Models.Productos", "Productos")
                        .WithMany("CategoriasProductos")
                        .HasForeignKey("productoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorias");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.ItemPedidoProductos", b =>
                {
                    b.HasOne("computerChip.Models.ItemPedido", "ItemPedido")
                        .WithMany("ItemPedidoProductos")
                        .HasForeignKey("itemPedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("computerChip.Models.Productos", "Productos")
                        .WithMany("ItemsPedidoProductos")
                        .HasForeignKey("productoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemPedido");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.PedidosItemPedido", b =>
                {
                    b.HasOne("computerChip.Models.ItemPedido", "ItemPedido")
                        .WithMany("PedidosItemPedido")
                        .HasForeignKey("itemPedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("computerChip.Models.Pedidos", "Pedidos")
                        .WithMany("PedidosItemPedido")
                        .HasForeignKey("pedidosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemPedido");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.ProductosAtributos", b =>
                {
                    b.HasOne("computerChip.Models.Atributos", "Atributos")
                        .WithMany("ProductosAtributos")
                        .HasForeignKey("atributoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("computerChip.Models.Productos", "Productos")
                        .WithMany("ProductoAtributos")
                        .HasForeignKey("productoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atributos");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.ProductosEspecificaciones", b =>
                {
                    b.HasOne("computerChip.Models.Especificaciones", "Especificaciones")
                        .WithMany("ProductosEspecificaciones")
                        .HasForeignKey("especificacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("computerChip.Models.Productos", "Productos")
                        .WithMany("ProductosEspecificaciones")
                        .HasForeignKey("productoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especificaciones");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.ProductosImagenes", b =>
                {
                    b.HasOne("computerChip.Models.Imagenes", "Imagenes")
                        .WithMany("ProductosImagenes")
                        .HasForeignKey("imagenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("computerChip.Models.Productos", "Productos")
                        .WithMany("ProductosImagenes")
                        .HasForeignKey("productoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imagenes");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.ProductosMarcas", b =>
                {
                    b.HasOne("computerChip.Models.Marcas", "Marcas")
                        .WithMany("ProductosMarcas")
                        .HasForeignKey("marcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("computerChip.Models.Productos", "Productos")
                        .WithMany("ProductosMarcas")
                        .HasForeignKey("productoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marcas");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.ProductosOfertas", b =>
                {
                    b.HasOne("computerChip.Models.Ofertas", "Ofertas")
                        .WithMany("ProductosOfertas")
                        .HasForeignKey("ofertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("computerChip.Models.Productos", "Productos")
                        .WithMany("ProductosOfertas")
                        .HasForeignKey("productoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ofertas");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("computerChip.Models.TablasIntermedias.ProductosPreguntas", b =>
                {
                    b.HasOne("computerChip.Models.Preguntas", "Preguntas")
                        .WithMany("ProductosPreguntas")
                        .HasForeignKey("preguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("computerChip.Models.Productos", "Productos")
                        .WithMany("ProductosPreguntas")
                        .HasForeignKey("productoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preguntas");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("computerChip.Models.Admin", b =>
                {
                    b.Navigation("PushTokens");
                });

            modelBuilder.Entity("computerChip.Models.Atributos", b =>
                {
                    b.Navigation("ProductosAtributos");
                });

            modelBuilder.Entity("computerChip.Models.Carrito", b =>
                {
                    b.Navigation("CarritoProductos");
                });

            modelBuilder.Entity("computerChip.Models.Categorias", b =>
                {
                    b.Navigation("CategoriasProductos");
                });

            modelBuilder.Entity("computerChip.Models.Especificaciones", b =>
                {
                    b.Navigation("ProductosEspecificaciones");
                });

            modelBuilder.Entity("computerChip.Models.Imagenes", b =>
                {
                    b.Navigation("ProductosImagenes");
                });

            modelBuilder.Entity("computerChip.Models.ItemPedido", b =>
                {
                    b.Navigation("ItemPedidoProductos");

                    b.Navigation("PedidosItemPedido");
                });

            modelBuilder.Entity("computerChip.Models.Marcas", b =>
                {
                    b.Navigation("ProductosMarcas");
                });

            modelBuilder.Entity("computerChip.Models.MetodoPago", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("computerChip.Models.Ofertas", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("ProductosOfertas");
                });

            modelBuilder.Entity("computerChip.Models.Pedidos", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("PedidosItemPedido");
                });

            modelBuilder.Entity("computerChip.Models.Preguntas", b =>
                {
                    b.Navigation("ProductosPreguntas");
                });

            modelBuilder.Entity("computerChip.Models.Productos", b =>
                {
                    b.Navigation("CarritoProductos");

                    b.Navigation("CategoriasProductos");

                    b.Navigation("ItemsPedidoProductos");

                    b.Navigation("ProductoAtributos");

                    b.Navigation("ProductosEspecificaciones");

                    b.Navigation("ProductosImagenes");

                    b.Navigation("ProductosMarcas");

                    b.Navigation("ProductosOfertas");

                    b.Navigation("ProductosPreguntas");
                });

            modelBuilder.Entity("computerChip.Models.Usuarios", b =>
                {
                    b.Navigation("Carrito");

                    b.Navigation("LoginGoogle");

                    b.Navigation("Pedidos");

                    b.Navigation("PushTokens");

                    b.Navigation("SantanderTokens");
                });

            modelBuilder.Entity("computerChip.Models.ZonaEnvio", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
